version: "3.9"

services: 
  database:
    container_name: ecommerce_db
    image: postgres
    environment:
      - POSTGRES_USER=morcegoUser
      - POSTGRES_PASSWORD=morcegoPassword
      - POSTGRES_DB=morcegoDB
    ports:
      - 5432:5432